### ISSUE TITLE
Add Google Authentication in Login and SignUp page

### ISSUE THREAD

**Issue by Chelsea67jain** [Priyaaa1/StartConnect-Hub#143]
I observed that the login page does not have a Login with Google Button. Most websites use this functionality to enhance the User Experience and provide ease to the user. I can add this feature using Firebase in this project. 
I am proficient in React.js, Node.js and MySQL. Also, I have worked on an e-commerce platform previously.

Below is the link of the GitHub repository:
https://github.com/Chelsea67jain/the_ultimate_garments

Screenshot:

![Screenshot (518)](https://github.com/Priyaaa1/StartConnect-Hub/assets/100270122/3945efcf-4721-4067-ba4f-18b6df1b946c)

![Screenshot (520)](https://github.com/Priyaaa1/StartConnect-Hub/assets/100270122/336c975b-2990-4d1c-8e3f-f9eaf6d1450d)

@Priyaaa1 Can you allocate me this task under GSSoC2024?

**Comment by K-Svayam05** [comment]
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/141111900/3baf3c7e-5d7e-481a-a943-bd2a638b91b8)

In addition to the above mentioned issue, I would also like to add that the email field is accepting any bizarre input instead of following a particular pattern.
Please assign this issue to me!
I am a GSSoC'24 Contributor, proficient in HTML, CSS, Javascript and having good knowledge of React.js as well as Web Design!
You can also assign me any other issues as well! Would love to work on this project!

**Comment by Isha1233** [comment]
@Priyaaa1 kindly assign this task to me I had worked on this type of project previously

**Comment by n14rishitha** [comment]
@Priyaaa1 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
