### ISSUE TITLE
 Add Scroll Bar (Vertical) and Scroll-to-Top Button to Website

### ISSUE THREAD

**Issue by MastanSayyad** [Priyaaa1/StartConnect-Hub#59]
Hi @Priyaaa1 
I've noticed that the website is missing a **vertical scroll bar** allowing users to scroll up and down as needed. 
Additionally, implementing a **scroll-to-top button** can enhance user experience by providing a convenient way for users to quickly return to the top of the page.

**Benefits of adding a scroll bar and scroll-to-top button,**

- Improved User Experience.
- Enhanced Accessibility.
- A vertical scroll bar and scroll-to-top button demonstrates attention to detail.
- These features contribute to a positive first impression of the website.

 As a GGSoC'24 contributor I'd like to take on the task, Could you please assign this project to me so I can start working on it?

**Comment by zaidihusain** [comment]
Hey there, @Priyaaa1 ,
I've noticed an opportunity to improve the website's usability by adding an interactive eye-catching custom vertical scroll bar and a scroll-to-top button, matching your UI . These features are essential for enhancing user navigation and overall experience on the site.
As a contributor to GGSoC'24, I'm eager to take on this task and contribute to the project's success. Could you please assign this issue to me so that I can begin working on it?
