### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by achlbatra** [Priyaaa1/StartConnect-Hub#62]
Please assign me this under GSSOC'24

**Comment by Techkunjan** [comment]
@Priyaaa1 Can you please assign the task to me as I am a newbie in open source.

**Comment by aasthakourav20** [comment]
Hey @Priyaa1 , A README file is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers
By consolidating all critical information in one place, a README file significantly improves the user experience and facilitates effective project management. 
Kindly assign this task to me under GSSoC'24
